OLLAMA_URL="http://localhost:11434"

JSON_OUTPUT_PATH="./json_generated_data"
SAVE_MARKDOWN_FILES=True
MARKDOWN_OUTPUT_PATH="./markdown"

MAX_STEPS=100
PLANNING_INTERVAL=10

MANAGER_MODEL="gpt-4.1-mini"
ANALYST_MODEL="o3"
IDEAS_CREATOR_MODEL="Bielik-11B-v2.6-Instruct:Q8_0"
TEXT_GENERATOR_MODEL="Bielik-11B-v2.6-Instruct:Q8_0"

MAP_REDUCE_MODEL = "Bielik-11B-v2.6-Instruct:Q8_0"
MAP_REDUCE_CONTEXT_WINDOW=10_000
